name: Radar Minero

on:

  schedule:
    - cron: '0 */6 * * *'

  workflow_dispatch:


jobs:

  run:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: instalar

      run: pip install requests beautifulsoup4

    - name: ejecutar radar

      run: python RADAR_MINERO_PRO.py

      env:

        TELEGRAM_TOKEN: ${{ secrets.TOKEN }}

        TELEGRAM_CHAT_ID: ${{ secrets.CHAT_ID }}        run: python radar.py
