name: Radar Minero

on:
  workflow_dispatch:

  schedule:
    - cron: '0 */6 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Instalar Python

        uses: actions/setup-python@v5

        with:
          python-version: '3.11'

      - name: Instalar librerias

        run: |
          pip install requests beautifulsoup4 python-telegram-bot

      - name: Ejecutar Radar

        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

        run: python radar.py
