name: Radar Minero

on:

  schedule:
    - cron: '0 */6 * * *'

  workflow_dispatch:


jobs:

  run:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: run radar

      run: python radar.py
     
      env:

    - TOKEN: ${{ secrets.TOKEN }}

    - CHAT_ID: ${{ secrets.CHAT_ID }}

 
